on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - 'ITA/Views'

jobs:
  find_changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      with:
        filters: |
          views:
            - '**/Views/'

        list-files: json

    - run: echo ${{ steps.filter.outputs.changed_files }}