name: FileFilter

on:
  # workflow_dispatch:
  push:
    paths:
      - '**/Views/**'

jobs:
  find_changes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      with:
        filters: |
          views:
            - '**/Views/**'

        list-files: json


  handle_changes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        notebook_path: ${{ steps.filter.outputs.changed_files }}
    
    steps:
      - uses: actions/checkout@v4
      # - name: Azure Login
      #   uses: Azure/login@v1
      #   with:
      #     creds: ${{ secrets.DEV_AZURE_CREDENTIALS }}
      - run: echo ${{ matrix.notebook_path }} >> $GITHUB_OUTPUT
      
      # - name: Run notebook
      #   uses: databricks/run-notebook@v0
      #   with:
      #     local-notebook-path: ${{ matrix.notebook_path }}