name: FileFilter

on:
  # workflow_dispatch:
  push:
    paths:
      - '**/Views/**'

jobs:
  find_changes:
    runs-on: ubuntu-latest
    outputs:
      changed_notebooks: ${{steps.changed_notebooks.outputs.changed_notebooks}}
      deleted_notebooks: ${{steps.deleted_notebooks.outputs.deleted_notebooks}}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          addedOrModifiedViews:
            - added|modified: '**/Views/**'
          deletedViews:
            - deleted: '**/Views/**'
        list-files: json
    - id: changed_notebooks
      run: echo "changed_notebooks=${{toJson(steps.filter.outputs.addedOrModifiedViews_files)}}" >> "$GITHUB_OUTPUT"
    - id: deleted_notebooks
      run: echo "deleted_notebooks=${{toJson(steps.filter.outputs.deletedViews_files)}}" >> "$GITHUB_OUTPUT"S



  handle_added_modified:
    if: ${{ needs.find_changes.outputs.changed_notebooks != '' && needs.find_changes.outputs.changed_notebooks != '[]' }}
    runs-on: ubuntu-latest
    needs: find_changes
    strategy:
      matrix:
        notebook_path: ${{fromJson(needs.find_changes.outputs.changed_notebooks)}}
    
    steps:
    - uses: actions/checkout@v4
    - name: Check notebook for syntax
      run: |
        python .github/workflows/createupdate.py "${{ matrix.notebook_path }}"
    # - name: Azure Login
    #   uses: Azure/login@v1
    #   with:
    #     creds: ${{ secrets.DEV_AZURE_CREDENTIALS }}
    
    # - name: Run notebook
    #   uses: databricks/run-notebook@v0
    #   with:
    #     local-notebook-path: ${{ matrix.notebook_path }}

  handle_deleted:
    if: ${{ needs.find_changes.outputs.deleted_notebooks != '' && needs.find_changes.outputs.deleted_notebooks != '[]' }}
    runs-on: ubuntu-latest
    needs: find_changes
    strategy:
      matrix:
        notebook_path: ${{fromJson(needs.find_changes.outputs.deleted_notebooks)}}

    steps: 
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.before }}