name: FileFilter

on:
  # workflow_dispatch:
  push:
    paths:
      - '**/Views/**'

jobs:
  find_changes:
    runs-on: ubuntu-latest
    outputs:
      changed_notebooks: ${{ steps.notebook_paths.outputs.changed_notebooks }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          views:
            - '**/Views/**'

        list-files: json
    - id: notebook_paths
      run: echo "changed_notebooks=${{ steps.filter.outputs.views_files }}" >> "$GITHUB_OUTPUT"


  handle_changes:
    runs-on: ubuntu-latest
    needs: find_changes
    strategy:
      matrix:
        notebook_path: ${{ fromJson(toJson(needs.find_changes.outputs.changed_notebooks)) }}
    
    steps:
      - uses: actions/checkout@v4
      # - name: Azure Login
      #   uses: Azure/login@v1
      #   with:
      #     creds: ${{ secrets.DEV_AZURE_CREDENTIALS }}
      - run: echo ${{ matrix.notebook_path }} >> $GITHUB_OUTPUT
      
      # - name: Run notebook
      #   uses: databricks/run-notebook@v0
      #   with:
      #     local-notebook-path: ${{ matrix.notebook_path }}
